server: 
 port: 7001
 
eureka: 
 instance: 
  hostname: localhost
 client: 
  register-with-eureka: false            #false表示不向注册中心注册自己
  fetch-registry: false                  #false表示自己端就是祖册中心，我的职责是维护服务实例，并不需要去检索服务
  service-url: 
   #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/                        #单机
   defaultZone: http://localhost:7001/eureka/ #,http://localhost:8001/eureka/    #集群
   
