server: 
  port: 3344 
  
spring:
  application:
    name:  superporject
  cloud:
    config:
      server:
        git:
          uri: git@github.com:superManJ/superporject.git #GitHub上面的git仓库名字