server: 
  port: 9527
 
spring: 
  application:
    name: supermap-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:7001/eureka#,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
 
zuul: 
  #ignored-services: supermap-dept
  prefix: /super        #通用前缀   
  ignored-services: "*" #关闭源域名
  routes: 
    mydept.serviceId: supermap-dept #key 域名
    mydept.path: /map/**			#value new域名			
 
info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: zhylb_SC_zuul
  build.version: 0.0.1-SNAPSHOT

